### ISSUE TITLE
Fail to build under Java17

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#222] opened 2021-09-29 15:53 UTC
```
Chronicle-Bytes % mvn test -Pjava11,java17 -Dtest=UnsafeRWObjectTest


[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running net.openhft.chronicle.bytes.UnsafeRWObjectTest
[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/Users/pemi/.m2/repository/net/openhft/chronicle-core/2.22ea7-SNAPSHOT/chronicle-core-2.22ea7-SNAPSHOT.jar
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.134 s <<< FAILURE! - in net.openhft.chronicle.bytes.UnsafeRWObjectTest
[ERROR] net.openhft.chronicle.bytes.UnsafeRWObjectTest.longObject  Time elapsed: 0.09 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<00000000 0[1 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00 ········ ········
00000010 03 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00 ········ ········
00000020 05 00 00 00 00 00 00 00  06 00 00 00 00 00 00 00 ········ ········
00000030 07 00 00 00 00 00 00 00  08] 00 00 00 00 00 00 0...> but was:<00000000 0[8 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00 ········ ········
00000010 03 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00 ········ ········
00000020 05 00 00 00 00 00 00 00  06 00 00 00 00 00 00 00 ········ ········
00000030 07 00 00 00 00 00 00 00  01] 00 00 00 00 00 00 0...>
	at net.openhft.chronicle.bytes.UnsafeRWObjectTest.longObject(UnsafeRWObjectTest.java:47)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   UnsafeRWObjectTest.longObject:47 expected:<00000000 0[1 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00 ········ ········
00000010 03 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00 ········ ········
00000020 05 00 00 00 00 00 00 00  06 00 00 00 00 00 00 00 ········ ········
00000030 07 00 00 00 00 00 00 00  08] 00 00 00 00 00 00 0...> but was:<00000000 0[8 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00 ········ ········
00000010 03 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00 ········ ········
00000020 05 00 00 00 00 00 00 00  06 00 00 00 00 00 00 00 ········ ········
00000030 07 00 00 00 00 00 00 00  01] 00 00 00 00 00 00 0...>
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.065 s
[INFO] Finished at: 2021-09-29T17:42:40+02:00
[INFO] ------------------------------------------------------------------------

```

**Comment by JerryShea** [comment] 2021-09-30 00:29
If you build with Java 8 and run with `mvn surefire:test -Pjava11,java17 -Dtest=UnsafeRWObjectTest` then it works OK

**Comment by minborg** [comment] 2021-09-30 06:10
Yes. I built it under Java17 and then tested it. Still, it might point to a real problem and I think it's worth investigating.

**Comment by JerryShea** [comment] 2021-10-28 04:51
Hmmmm I just built and ran the test under Java 17 and it was fine

**Comment by JerryShea** [comment] 2021-12-08 21:39
@minborg can we close this as I could not reproduce

**Comment by minborg** [comment] 2021-12-09 08:27
```
mvn clean install -Pjava11,java17

[ERROR] Failures: 
[ERROR]   UnsafeRWObjectTest.longObject:47 expected:<00000000 0[1 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00 ········ ········
00000010 03 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00 ········ ········
00000020 05 00 00 00 00 00 00 00  06 00 00 00 00 00 00 00 ········ ········
00000030 07 00 00 00 00 00 00 00  08] 00 00 00 00 00 00 0...> but was:<00000000 0[8 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00 ········ ········
00000010 03 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00 ········ ········
00000020 05 00 00 00 00 00 00 00  06 00 00 00 00 00 00 00 ········ ········
00000030 07 00 00 00 00 00 00 00  01] 00 00 00 00 00 00 0...>
[ERROR] Errors: 
[ERROR]   BytesFieldInfoTest.lookup:15 » IllegalState The header FieldGroup must be at t...
[INFO] 
[ERROR] Tests run: 2258, Failures: 1, Errors: 1, Skipped: 27


```

**Comment by peter-lawrey** [comment] 2022-03-17 14:21
On `develop` it appears to be passing now.

```
peter@dev-a:~/Build-All/Chronicle-Bytes$ java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
peter@dev-a:~/Build-All/Chronicle-Bytes$ mvn clean install -Pjava11,java17

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:09 min
[INFO] Finished at: 2022-03-17T14:20:29Z
[INFO] ------------------------------------------------------------------------
```

**Closed as completed by peter-lawrey** 2022-03-17 14:21 UTC
Labels: bug
